---
- name: Install PostgreSQL (Debian & AlmaLinux without key imports)
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: yes

  tasks:
    - name: Install PostgreSQL (Debian)
      block:
        - name: Update apt cache
          apt:
            update_cache: yes

        - name: Install PostgreSQL
          apt:
            name: postgresql
            state: present
      when: ansible_os_family == "Debian"

    - name: Install PostgreSQL (AlmaLinux)
      block:
        - name: Install from default repositories
          yum:
            name:
              - postgresql-server
              - postgresql
            state: present

        - name: Initialize database (AlmaLinux 9)
          command: postgresql-setup initdb
          args:
            creates: /var/lib/pgsql/data/PG_VERSION
          when: ansible_distribution_major_version|int >= 8

      when: ansible_os_family == "RedHat"

    - name: Start and enable PostgreSQL
      service:
        name: postgresql
        state: started
        enabled: yes