Vagrant.configure("2") do |config|
  # Настройки Debian
  config.vm.define "debian" do |debian|
    debian.vm.box = "debian/bookworm64"
    debian.vm.hostname = "debian"
    debian.vm.network "forwarded_port", guest: 22, host: 2222, id: "ssh"

    debian.vm.provision "shell", inline: <<-SHELL
      echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
      echo "PasswordAuthentication no" >> /etc/ssh/sshd_config
      systemctl restart ssh
      usermod --password '*' root
      mkdir -p /root/.ssh
      echo '#{File.read(File.expand_path("~/.ssh/id_rsa.pub"))}' > /root/.ssh/authorized_keys
      chmod 600 /root/.ssh/authorized_keys
      chmod 700 /root/.ssh
    SHELL
  end

  config.vm.define "almalinux" do |almalinux|
    almalinux.vm.box = "almalinux/9"
    almalinux.vm.hostname = "almalinux"
    almalinux.vm.network "forwarded_port", guest: 22, host: 2223, id: "ssh"

    almalinux.vm.provision "shell", inline: <<-SHELL
      sed -i 's/^#PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config
      sed -i 's/^#PasswordAuthentication.*/PasswordAuthentication no/' /etc/ssh/sshd_config
      systemctl restart sshd
      mkdir -p /root/.ssh
      echo '#{File.read(File.expand_path("~/.ssh/id_rsa.pub"))}' > /root/.ssh/authorized_keys
      chmod 600 /root/.ssh/authorized_keys
      chmod 700 /root/.ssh
    SHELL
  end
end

